version: '3.8'

services:
  db:
    image: postgres:16
    container_name: slowka_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: latarka
    ports:
      - "5432:5432"
    volumes:
      - ./backupSlowka2.sql:/docker-entrypoint-initdb.d/backupSlowka2.sql
