package umk.mat.jakuburb.database;

public enum StanyDatabase {
    NULL,
    ZAPIS_SLOWEK,
    ZAPIS_ZESTAWU,
    ODCZYT_SLOWEK,
    USUN_ZESTAW,
    UPDATE_SLOWKA,
    DELETE_SLOWKO,

    GET_ZESTAWY,
    HOME_WYKRES_POGRESS,
    RANDOM_WORD,
    THE_BEST,
    THE_WORST,

    READ_CALENDAR,
    UPDATE_CALENDAR,
    CREATE_CALENDAR,

    CREATE_GAME,
    SAVE_ROUND,
    CALENDAR_GAME,
    END_GAME
}